# -*- coding: utf-8 -*-
"""Promedio aritmético.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iv237h1ZZC7C0P-kHeIVlJ233S4T9Kpx
"""

def promedio(lista):
  x = 0
  for elem in lista:
   x += elem
  prom = x/(len(lista))
  return prom